- endpoint: buckets.idrinth.de/test-01
  bucket: test-01
  access-key: abcdefghijklmnopqrstuvwxyz
  secret-access-key: 1234567890
  targets:
  - endpoint: buckets.idrinth.de/test-02
    bucket: test-02
    access-key: abcdefghijklmnopqrstuvwxyz
    secret-access-key: 1234567890